from pathlib import Path

PASTA_CODIGO = Path(__file__).resolve().parent  # PASTA CODIGO
PASTA_BASE      = PASTA_CODIGO.parent           # PASTA TESER

PASTA_DADOS     = PASTA_BASE / "DADOS"          # PASTA DADOS
PASTA_ARQUIVOS  = PASTA_BASE / "ARQUIVOS"       # PASTA ARQUIVOS
PASTA_SAIDA     = PASTA_BASE / "SAIDA"          # PASTA SAIDA

PASTA_REC = PASTA_ARQUIVOS / "REC"              # PASTA REC
PASTA_REQ = PASTA_ARQUIVOS / "REQ"              # PASTA REQ
PASTA_OFI = PASTA_ARQUIVOS / "OFI"              # PASTA OFI

PLANILHA_DADOS_DOS_MUNICIPIOS = PASTA_DADOS / "DADOS DOS MUNICÍPIOS.xlsx"  # PLANILHA DADOS DOS MUNICIPIOS

